### ISSUE TITLE
How does one properly initialize?

### ISSUE THREAD

**Issue by gchustz** [jpl-x/x_vio_ros#3]
I've had luck with implementing XVIO ros on Noetic and wanted to ask about how to properly initialize XVIO.
I am unclear on how to trigger the initialization without the init_on_startup parameter enabled. Is there an acceleration threshold which needs to be exceeded?

When starting from a level surface with the init_on_startup = True, the propagation immediately accelerates along the gravity vector, I verified that the accelerometer and the gravity vector in the source code have aligned Z axes. (+Z = up, gravity ={0,0,9.81}).

Are the gravity vector, biases, and initial orientation estimated during the initialization or is it assuming the parameters are correct?

And for every dataset, do I need to be specific about the gyro and accelerometer biases and the orientation, or will the estimator converge fast enough to allow for rough estimates?

**Comment by jeff-delaune** [comment]
Hi @gchustz ,

Happy to hear you are able to execute xVIO on Noetic! Let me try to answer your questions.

"I am unclear on how to trigger the initialization without the init_on_startup parameter enabled" => We We implemented a GUI button for easy (re-)initialization in ROS' dynamic reconfigure. Run scripts/load_gui.sh to use the recommended GUI.

"the propagation immediately accelerates along the gravity vector" => That sounds like an initial orientation error. xVIO assumes the gravity is along -Z axis. That means the reaction to gravity is along +Z if your vehicle is initially static. If a vehicle is perfectly upright as you describe that means a unit quaternion should be a correct initialization (initial heading doesn't matter in VIO). Does that sound like the configuration you have?

"Are the gravity vector, biases, and initial orientation estimated during the initialization or is it assuming the parameters are correct?" => Assuming initial parameters are correcting, +/- the initial uncertainty modeled in vio.cpp. With all IMUs we've been testing, biases converge on their own from a zero initalization (providing excitation), and initial orientation has to be accurate +/- ~20 deg with current initial covariance settings.

Let me know if that helps!

**Comment by gchustz** [comment]
Hello again,

I have returned to this issue and I'm still having a bit of trouble, is it possible that I can get a sample ros bag and the associated configuration file?

**Comment by jeff-delaune** [comment]
Sure, there is actually a sample dataset and set of instructions on the wiki here: https://github.com/jpl-x/x/wiki/xvio-ros

**Comment by gchustz** [comment]
Thank you for the link! 

I was able to get your data running instantly, and after some comparison I was able to get my data set running. 

Feel free to comment further with any tuning tips as I will be working on that now.

Thanks again!
